export const MOCKDATA_COMPANY = [
  {
    name: "Binh Thuan Nha Be Garment JSC",
    shortName: "Binh Thuan Nha Be",
    taxCode: "3400408976",
    website: "http://binhthuannhabe.com",
    email: "binhthuannhabeJSC16@binhthuannhabe.com",
    emailOwner: "binhthuannhabeJSC16@binhthuannhabe.com",
    phoneNumber: "84-252-3871922",
    status: "public",
    province: "Binh Thuan",
    companyBranchDtoList: [
      {
        branchName: " Ha Noi Head Office",
        address: "204 Thong Nhat Str., Tan Thien Ward, La Gi Town, Binh Thuan",
        isHeadOffice: true,
        longitude: "21.027",
        latitude: "105.85227",
      },
      {
        branchName: "HCM Branch",
        address: "123 Nguyen Van Cu, District 5, Ho Chi Minh City",
        isHeadOffice: false,
        longitude: "99.0110",
        latitude: "203.22089",
      },
    ],
    introduction: "Đây là công ty Binh Thuan Nha Be Garment JSC ",
    urlVideo: "abc.com",
    manufacturingSector: "Men Shirt; Overcoats; Trousers; Sport Wears",
    productionModels: "FOB, CMT",
    keyProducts:
      "Men shirts: 2,800,000 pcs/year Overcoats, Sport wears: 1,200,000 pcs/year, Trousers: 7,000,000 pcs/year",
    manufacturingMarket:
      "Colombia, Adidas, Nike, Puma, Marmot, Mont-Bell, The North Face, Christian Orani, Champion, Farago, Everlast, Karrimor, Algle, Tommy Hilfiger",
    annualCapacity: "test,tes1",
    numberOfEmployees: 4600,
    productionScale: "test,tes1",
    exportBrand: "like,adidas",
    companyCertification: "ISO 9001, SA 8000, WRAP",
  },
  {
    name: "Dong Nai Textile Corporation",
    shortName: "Dong Nai Textile",
    province: "Dong Nai",
    taxCode: "3600789123",
    website: "http://dongnaitextile.vn",
    email: "info@dongnaitextile.vn",
    emailOwner: "ceo@dongnaitextile.vn",
    phoneNumber: "84-261-3892456",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Dong Nai Head Office",
        address: "45 Pham Van Thuan, Bien Hoa City, Dong Nai",
        isHeadOffice: true,
        longitude: "106.824",
        latitude: "10.9477",
      },
      {
        branchName: "Can Tho Branch",
        address: "67 Tran Hung Dao, Can Tho City",
        isHeadOffice: false,
        longitude: "105.7851",
        latitude: "10.0346",
      },
    ],
    introduction: "Leading textile manufacturer in Dong Nai province",
    urlVideo: "dongnaitextile.vn/video",
    manufacturingSector: "Women's Dresses; Blouses; Skirts; Formal Wear",
    productionModels: "FOB, ODM",
    keyProducts:
      "Women's dresses: 1,500,000 pcs/year, Blouses: 2,200,000 pcs/year, Skirts: 800,000 pcs/year",
    manufacturingMarket:
      "H&M, Zara, Uniqlo, Gap, Mango, Massimo Dutti, Bershka",
    annualCapacity: "5.2 million pieces",
    numberOfEmployees: 3200,
    productionScale: "Large scale production",
    exportBrand: "H&M, Zara",
    companyCertification: "ISO 9001, OEKO-TEX, GOTS",
  },
  {
    name: "Vinatex Fashion Group",
    shortName: "Vinatex Fashion",
    taxCode: "1000456789",
    website: "http://vinatexfashion.com",
    email: "contact@vinatexfashion.com",
    emailOwner: "director@vinatexfashion.com",
    phoneNumber: "84-24-3943567",
    province: "Hanoi",
    status: "reviewer",
    companyBranchDtoList: [
      {
        branchName: "Hanoi Headquarters",
        address: "12 Ly Thuong Kiet, Hoan Kiem, Hanoi",
        isHeadOffice: true,
        longitude: "105.8542",
        latitude: "21.0285",
      },
      {
        branchName: "Da Nang Branch",
        address: "89 Bach Dang, Hai Chau, Da Nang",
        isHeadOffice: false,
        longitude: "108.2208",
        latitude: "16.0544",
      },
    ],
    introduction: "Premier fashion manufacturer with 40 years of experience",
    urlVideo: "vinatexfashion.com/about",
    manufacturingSector: "Casual Wear; Jeans; Jackets; Accessories",
    productionModels: "FOB, CMT, ODM",
    keyProducts:
      "Jeans: 3,500,000 pcs/year, Jackets: 900,000 pcs/year, Casual wear: 2,800,000 pcs/year",
    manufacturingMarket:
      "Levi's, Wrangler, Lee, Diesel, Calvin Klein, Hugo Boss",
    annualCapacity: "8.5 million pieces",
    numberOfEmployees: 5800,
    productionScale: "Industrial scale",
    exportBrand: "Levi's, Calvin Klein",
    companyCertification: "ISO 9001, ISO 14001, WRAP, BSCI",
  },
  {
    name: "Saigon Garment Manufacturing Co",
    shortName: "Saigon Garment",
    taxCode: "3100567890",
    website: "http://saigongarment.vn",
    email: "sales@saigongarment.vn",
    emailOwner: "owner@saigongarment.vn",
    phoneNumber: "84-28-3678901",
    province: "Ho Chi Minh City",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Ho Chi Minh Head Office",
        address: "156 Nguyen Thi Minh Khai, District 1, Ho Chi Minh City",
        isHeadOffice: true,
        longitude: "106.6917",
        latitude: "10.7769",
      },
    ],
    introduction:
      "Specialized in high-quality garment manufacturing since 1995",
    urlVideo: "saigongarment.vn/company-video",
    manufacturingSector: "Children's Wear; Baby Clothes; School Uniforms",
    productionModels: "FOB, CMT",
    keyProducts:
      "Children's wear: 1,800,000 pcs/year, Baby clothes: 1,200,000 pcs/year, Uniforms: 600,000 pcs/year",
    manufacturingMarket: "Carter's, Gerber, Gap Kids, H&M Kids, Next",
    annualCapacity: "4.2 million pieces",
    numberOfEmployees: 2400,
    productionScale: "Medium to large scale",
    exportBrand: "Carter's, Gap Kids",
    companyCertification: "ISO 9001, SA 8000, OEKO-TEX",
  },
  {
    name: "Hue Silk Textile Enterprise",
    shortName: "Hue Silk",
    taxCode: "4600234567",
    website: "http://huesilk.com.vn",
    email: "info@huesilk.com.vn",
    emailOwner: "ceo@huesilk.com.vn",
    phoneNumber: "84-234-3567890",
    province: "Thua Thien Hue",
    status: "cancelation",
    companyBranchDtoList: [
      {
        branchName: "Hue Head Office",
        address: "78 Le Loi, Hue City, Thua Thien Hue",
        isHeadOffice: true,
        longitude: "107.5955",
        latitude: "16.4637",
      },
      {
        branchName: "Hoi An Workshop",
        address: "23 Tran Phu, Hoi An, Quang Nam",
        isHeadOffice: false,
        longitude: "108.3269",
        latitude: "15.8801",
      },
    ],
    introduction:
      "Traditional silk manufacturer preserving Vietnamese heritage",
    urlVideo: "huesilk.com.vn/heritage",
    manufacturingSector:
      "Silk Garments; Traditional Ao Dai; Scarves; Home Textiles",
    productionModels: "FOB, ODM, OEM",
    keyProducts:
      "Silk garments: 450,000 pcs/year, Ao Dai: 280,000 pcs/year, Scarves: 800,000 pcs/year",
    manufacturingMarket:
      "Luxury boutiques, Traditional wear brands, Export to Japan, Korea",
    annualCapacity: "1.8 million pieces",
    numberOfEmployees: 1200,
    productionScale: "Artisan to medium scale",
    exportBrand: "Premium silk brands",
    companyCertification: "ISO 9001, GOTS, Silk Mark",
  },
  {
    name: "Mekong Delta Apparel Ltd",
    shortName: "Mekong Apparel",
    taxCode: "9200345678",
    website: "http://mekongapparel.vn",
    email: "export@mekongapparel.vn",
    emailOwner: "manager@mekongapparel.vn",
    phoneNumber: "84-292-3456789",
    province: "Can Tho",
    status: "reviewer",
    companyBranchDtoList: [
      {
        branchName: "Can Tho Head Office",
        address: "234 3/2 Street, Ninh Kieu District, Can Tho",
        isHeadOffice: true,
        longitude: "105.7851",
        latitude: "10.0346",
      },
      {
        branchName: "An Giang Branch",
        address: "56 Nguyen Hue, Long Xuyen, An Giang",
        isHeadOffice: false,
        longitude: "105.4349",
        latitude: "10.3816",
      },
    ],
    introduction: "Sustainable apparel manufacturer in the Mekong Delta region",
    urlVideo: "mekongapparel.vn/sustainability",
    manufacturingSector: "Eco-friendly Clothing; Organic Cotton; Activewear",
    productionModels: "FOB, ODM",
    keyProducts:
      "Organic cotton wear: 1,100,000 pcs/year, Activewear: 750,000 pcs/year",
    manufacturingMarket: "Patagonia, Eileen Fisher, Prana, Organic brands",
    annualCapacity: "2.8 million pieces",
    numberOfEmployees: 1800,
    productionScale: "Sustainable production",
    exportBrand: "Patagonia, Prana",
    companyCertification: "GOTS, Fair Trade, B Corp",
  },
  {
    name: "Hanoi Fashion Industries",
    shortName: "Hanoi Fashion",
    taxCode: "1000678901",
    website: "http://hanoifashion.vn",
    email: "business@hanoifashion.vn",
    emailOwner: "ceo@hanoifashion.vn",
    phoneNumber: "84-24-3789012",
    province: "Hanoi",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Hanoi Head Office",
        address: "345 Kim Ma, Ba Dinh District, Hanoi",
        isHeadOffice: true,
        longitude: "105.8362",
        latitude: "21.0245",
      },
      {
        branchName: "Hai Phong Branch",
        address: "67 Dien Bien Phu, Hai Phong",
        isHeadOffice: false,
        longitude: "106.6881",
        latitude: "20.8449",
      },
    ],
    introduction: "Leading fashion manufacturer in Northern Vietnam",
    urlVideo: "hanoifashion.vn/profile",
    manufacturingSector: "Formal Wear; Business Suits; Coats; Luxury Garments",
    productionModels: "FOB, CMT, ODM",
    keyProducts:
      "Business suits: 600,000 pcs/year, Coats: 400,000 pcs/year, Formal wear: 850,000 pcs/year",
    manufacturingMarket: "Hugo Boss, Armani, Zegna, Brooks Brothers",
    annualCapacity: "2.5 million pieces",
    numberOfEmployees: 2200,
    productionScale: "High-end production",
    exportBrand: "Hugo Boss, Armani",
    companyCertification: "ISO 9001, WRAP, BSCI",
  },
  {
    name: "Quang Ninh Knitting Company",
    shortName: "Quang Ninh Knit",
    taxCode: "1400789012",
    website: "http://quangninhknit.com",
    email: "info@quangninhknit.com",
    emailOwner: "director@quangninhknit.com",
    phoneNumber: "84-203-3890123",
    province: "Quang Ninh",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Ha Long Head Office",
        address: "123 Ha Long Road, Ha Long City, Quang Ninh",
        isHeadOffice: true,
        longitude: "107.0431",
        latitude: "20.9101",
      },
    ],
    introduction: "Specialized knitting manufacturer with modern technology",
    urlVideo: "quangninhknit.com/technology",
    manufacturingSector: "Knitwear; Sweaters; T-shirts; Polo Shirts",
    productionModels: "FOB, CMT",
    keyProducts:
      "T-shirts: 4,200,000 pcs/year, Sweaters: 800,000 pcs/year, Polo shirts: 1,500,000 pcs/year",
    manufacturingMarket: "Polo Ralph Lauren, Lacoste, Tommy Hilfiger, Uniqlo",
    annualCapacity: "7.8 million pieces",
    numberOfEmployees: 3800,
    productionScale: "Large scale knitting",
    exportBrand: "Polo Ralph Lauren, Lacoste",
    companyCertification: "ISO 9001, OEKO-TEX, WRAP",
  },
  {
    name: "Binh Duong Textile Joint Stock Company",
    shortName: "Binh Duong Textile",
    taxCode: "3700890123",
    website: "http://binhduongtextile.vn",
    email: "export@binhduongtextile.vn",
    emailOwner: "gm@binhduongtextile.vn",
    phoneNumber: "84-274-3901234",
    province: "Binh Duong",
    status: "reviewer",
    companyBranchDtoList: [
      {
        branchName: "Thu Dau Mot Head Office",
        address: "456 Binh Duong Avenue, Thu Dau Mot, Binh Duong",
        isHeadOffice: true,
        longitude: "106.6519",
        latitude: "10.9804",
      },
      {
        branchName: "Binh Chanh Branch",
        address: "789 Nguyen Van Linh, Binh Chanh, Ho Chi Minh City",
        isHeadOffice: false,
        longitude: "106.7297",
        latitude: "10.7307",
      },
    ],
    introduction:
      "Integrated textile manufacturer from yarn to finished garments",
    urlVideo: "binhduongtextile.vn/integration",
    manufacturingSector: "Denim; Casual Pants; Workwear; Uniforms",
    productionModels: "FOB, CMT, ODM",
    keyProducts:
      "Denim: 2,800,000 pcs/year, Casual pants: 1,900,000 pcs/year, Workwear: 1,100,000 pcs/year",
    manufacturingMarket: "Levi's, Wrangler, Dickies, Carhartt, Lee",
    annualCapacity: "6.5 million pieces",
    numberOfEmployees: 4200,
    productionScale: "Integrated production",
    exportBrand: "Levi's, Dickies",
    companyCertification: "ISO 9001, ISO 14001, WRAP, Better Cotton",
  },
  {
    name: "Tay Ninh Garment Export Corporation",
    shortName: "Tay Ninh Garment",
    taxCode: "3700012345",
    website: "http://tayninhgarment.com",
    email: "sales@tayninhgarment.com",
    emailOwner: "president@tayninhgarment.com",
    phoneNumber: "84-276-3012345",
    province: "Tay Ninh",
    status: "cancelation",
    companyBranchDtoList: [
      {
        branchName: "Tay Ninh Head Office",
        address: "567 Cach Mang Thang 8, Tay Ninh City",
        isHeadOffice: true,
        longitude: "106.1067",
        latitude: "11.3103",
      },
    ],
    introduction: "Export-oriented garment manufacturer near Cambodia border",
    urlVideo: "tayninhgarment.com/export",
    manufacturingSector: "Swimwear; Beach Wear; Resort Wear; Lingerie",
    productionModels: "FOB, ODM",
    keyProducts:
      "Swimwear: 850,000 pcs/year, Beach wear: 650,000 pcs/year, Lingerie: 1,200,000 pcs/year",
    manufacturingMarket: "Victoria's Secret, Speedo, Billabong, Roxy",
    annualCapacity: "3.2 million pieces",
    numberOfEmployees: 2100,
    productionScale: "Specialized production",
    exportBrand: "Victoria's Secret, Speedo",
    companyCertification: "ISO 9001, WRAP, OEKO-TEX",
  },
  {
    name: "Nam Dinh Textile Manufacturing",
    shortName: "Nam Dinh Textile",
    taxCode: "1800123456",
    website: "http://namdinhtext.vn",
    email: "contact@namdinhtext.vn",
    emailOwner: "ceo@namdinhtext.vn",
    phoneNumber: "84-228-3123456",
    province: "Nam Dinh",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Nam Dinh Head Office",
        address: "678 Tran Hung Dao, Nam Dinh City",
        isHeadOffice: true,
        longitude: "106.1675",
        latitude: "20.4388",
      },
      {
        branchName: "Thai Binh Branch",
        address: "234 Ly Bon, Thai Binh City",
        isHeadOffice: false,
        longitude: "106.3358",
        latitude: "20.4464",
      },
    ],
    introduction:
      "Traditional textile region manufacturer with modern facilities",
    urlVideo: "namdinhtext.vn/tradition",
    manufacturingSector: "Cotton Fabrics; Bed Linens; Table Linens; Curtains",
    productionModels: "FOB, OEM",
    keyProducts:
      "Bed linens: 1,800,000 sets/year, Table linens: 600,000 sets/year, Curtains: 400,000 sets/year",
    manufacturingMarket: "IKEA, Target, Walmart, Home Depot",
    annualCapacity: "3.5 million sets",
    numberOfEmployees: 2800,
    productionScale: "Home textile production",
    exportBrand: "IKEA, Target",
    companyCertification: "ISO 9001, GOTS, OEKO-TEX",
  },
  {
    name: "Hai Duong Fashion Enterprise",
    shortName: "Hai Duong Fashion",
    taxCode: "1300234567",
    website: "http://haiduongfashion.vn",
    email: "info@haiduongfashion.vn",
    emailOwner: "manager@haiduongfashion.vn",
    phoneNumber: "84-220-3234567",
    province: "Hai Duong",
    status: "reviewer",
    companyBranchDtoList: [
      {
        branchName: "Hai Duong Head Office",
        address: "789 Nguyen Du, Hai Duong City",
        isHeadOffice: true,
        longitude: "106.3147",
        latitude: "20.9373",
      },
    ],
    introduction: "Fashion manufacturer specializing in trendy youth clothing",
    urlVideo: "haiduongfashion.vn/youth",
    manufacturingSector:
      "Youth Fashion; Streetwear; Casual Wear; Trendy Clothes",
    productionModels: "FOB, ODM",
    keyProducts:
      "Youth fashion: 2,200,000 pcs/year, Streetwear: 900,000 pcs/year, Casual wear: 1,400,000 pcs/year",
    manufacturingMarket: "Urban Outfitters, Forever 21, H&M, Pull & Bear",
    annualCapacity: "5.1 million pieces",
    numberOfEmployees: 3100,
    productionScale: "Fast fashion production",
    exportBrand: "Urban Outfitters, H&M",
    companyCertification: "ISO 9001, WRAP, BSCI",
  },
  {
    name: "Long An Garment Industrial Park",
    shortName: "Long An Garment",
    taxCode: "3600345678",
    website: "http://longangarment.com",
    email: "business@longangarment.com",
    emailOwner: "director@longangarment.com",
    phoneNumber: "84-272-3345678",
    province: "Long An",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Tan An Head Office",
        address: "890 Hung Vuong, Tan An City, Long An",
        isHeadOffice: true,
        longitude: "106.4169",
        latitude: "10.5386",
      },
    ],
    introduction:
      "Industrial park-based garment manufacturer with modern facilities",
    urlVideo: "longangarment.com/facilities",
    manufacturingSector:
      "Industrial Uniforms; Safety Wear; Protective Clothing",
    productionModels: "FOB, CMT",
    keyProducts:
      "Industrial uniforms: 1,600,000 pcs/year, Safety wear: 800,000 pcs/year, Protective clothing: 500,000 pcs/year",
    manufacturingMarket: "3M, DuPont, Honeywell, MSA Safety",
    annualCapacity: "3.8 million pieces",
    numberOfEmployees: 2600,
    productionScale: "Industrial scale",
    exportBrand: "3M, DuPont",
    companyCertification: "ISO 9001, ISO 45001, WRAP",
  },
  {
    name: "Thanh Hoa Spinning & Weaving",
    shortName: "Thanh Hoa Textile",
    taxCode: "1900456789",
    website: "http://thanhhoatextile.vn",
    email: "export@thanhhoatextile.vn",
    emailOwner: "ceo@thanhhoatextile.vn",
    phoneNumber: "84-237-3456789",
    province: "Thanh Hoa",
    status: "cancelation",
    companyBranchDtoList: [
      {
        branchName: "Thanh Hoa Head Office",
        address: "123 Ba Trieu, Thanh Hoa City",
        isHeadOffice: true,
        longitude: "105.7765",
        latitude: "19.8007",
      },
      {
        branchName: "Nghe An Branch",
        address: "456 Le Loi, Vinh City, Nghe An",
        isHeadOffice: false,
        longitude: "105.6908",
        latitude: "18.6569",
      },
    ],
    introduction:
      "Integrated spinning and weaving company serving global markets",
    urlVideo: "thanhhoatextile.vn/integration",
    manufacturingSector: "Woven Fabrics; Dress Shirts; Formal Wear; Blouses",
    productionModels: "FOB, CMT, ODM",
    keyProducts:
      "Dress shirts: 1,800,000 pcs/year, Formal wear: 1,100,000 pcs/year, Blouses: 1,500,000 pcs/year",
    manufacturingMarket: "Brooks Brothers, Calvin Klein, Arrow, Van Heusen",
    annualCapacity: "5.4 million pieces",
    numberOfEmployees: 3600,
    productionScale: "Integrated textile production",
    exportBrand: "Brooks Brothers, Calvin Klein",
    companyCertification: "ISO 9001, WRAP, Better Cotton",
  },
  {
    name: "Vung Tau Coastal Garment Co",
    shortName: "Vung Tau Coastal",
    taxCode: "4300567890",
    website: "http://vungtaucoastal.vn",
    email: "info@vungtaucoastal.vn",
    emailOwner: "gm@vungtaucoastal.vn",
    phoneNumber: "84-254-3567890",
    province: "Ba Ria-Vung Tau",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Vung Tau Head Office",
        address: "234 Thuy Van, Vung Tau City, Ba Ria-Vung Tau",
        isHeadOffice: true,
        longitude: "107.0840",
        latitude: "10.3460",
      },
    ],
    introduction:
      "Coastal location manufacturer specializing in resort and cruise wear",
    urlVideo: "vungtaucoastal.vn/resort",
    manufacturingSector:
      "Resort Wear; Cruise Wear; Holiday Clothes; Light Garments",
    productionModels: "FOB, ODM",
    keyProducts:
      "Resort wear: 1,200,000 pcs/year, Cruise wear: 400,000 pcs/year, Holiday clothes: 800,000 pcs/year",
    manufacturingMarket: "Royal Caribbean, Celebrity Cruises, Resort brands",
    annualCapacity: "3.0 million pieces",
    numberOfEmployees: 1900,
    productionScale: "Specialized resort production",
    exportBrand: "Royal Caribbean, Celebrity",
    companyCertification: "ISO 9001, OEKO-TEX, WRAP",
  },
  {
    name: "Ninh Binh Traditional Craft",
    shortName: "Ninh Binh Craft",
    taxCode: "1500678901",
    website: "http://ninhbinhcraft.vn",
    email: "heritage@ninhbinhcraft.vn",
    emailOwner: "artisan@ninhbinhcraft.vn",
    phoneNumber: "84-229-3678901",
    province: "Ninh Binh",
    status: "reviewer",
    companyBranchDtoList: [
      {
        branchName: "Ninh Binh Head Office",
        address: "345 Tran Hung Dao, Ninh Binh City",
        isHeadOffice: true,
        longitude: "105.9745",
        latitude: "20.2506",
      },
    ],
    introduction:
      "Traditional craft manufacturer preserving Vietnamese embroidery techniques",
    urlVideo: "ninhbinhcraft.vn/heritage",
    manufacturingSector:
      "Embroidered Garments; Traditional Wear; Handicrafts; Cultural Clothes",
    productionModels: "OEM, ODM",
    keyProducts:
      "Embroidered garments: 300,000 pcs/year, Traditional wear: 150,000 pcs/year, Handicrafts: 200,000 pcs/year",
    manufacturingMarket:
      "Cultural centers, Museums, Traditional wear boutiques",
    annualCapacity: "850,000 pieces",
    numberOfEmployees: 600,
    productionScale: "Artisan production",
    exportBrand: "Cultural heritage brands",
    companyCertification: "Heritage Craft Certificate, Fair Trade",
  },
  {
    name: "Kien Giang Seafood Processing Garment",
    shortName: "Kien Giang Seafood",
    taxCode: "9100789012",
    website: "http://kiengiangseafood.vn",
    email: "processing@kiengiangseafood.vn",
    emailOwner: "owner@kiengiangseafood.vn",
    phoneNumber: "84-297-3789012",
    province: "Kien Giang",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Rach Gia Head Office",
        address: "456 Nguyen Trung Truc, Rach Gia City, Kien Giang",
        isHeadOffice: true,
        longitude: "105.0807",
        latitude: "10.0124",
      },
    ],
    introduction:
      "Unique combination of seafood processing and garment manufacturing",
    urlVideo: "kiengiangseafood.vn/dual-business",
    manufacturingSector:
      "Waterproof Clothing; Fishing Gear; Marine Uniforms; Workwear",
    productionModels: "FOB, CMT",
    keyProducts:
      "Waterproof clothing: 800,000 pcs/year, Marine uniforms: 500,000 pcs/year, Workwear: 600,000 pcs/year",
    manufacturingMarket: "Marine industry, Fishing companies, Outdoor brands",
    annualCapacity: "2.4 million pieces",
    numberOfEmployees: 1500,
    productionScale: "Marine specialized production",
    exportBrand: "Marine workwear brands",
    companyCertification: "ISO 9001, Marine Safety Standards",
  },
  {
    name: "Bac Ninh Electronics Garment",
    shortName: "Bac Ninh Electronics",
    taxCode: "1600890123",
    website: "http://bacninhelectronics.vn",
    email: "cleanroom@bacninhelectronics.vn",
    emailOwner: "tech@bacninhelectronics.vn",
    phoneNumber: "84-222-3890123",
    province: "Bac Ninh",
    status: "cancelation",
    companyBranchDtoList: [
      {
        branchName: "Bac Ninh Head Office",
        address: "567 Ly Thai To, Bac Ninh City",
        isHeadOffice: true,
        longitude: "106.0610",
        latitude: "21.1861",
      },
    ],
    introduction: "Specialized in cleanroom garments for electronics industry",
    urlVideo: "bacninhelectronics.vn/cleanroom",
    manufacturingSector:
      "Cleanroom Suits; Anti-static Clothing; Lab Coats; Tech Uniforms",
    productionModels: "FOB, ODM",
    keyProducts:
      "Cleanroom suits: 600,000 pcs/year, Anti-static clothing: 400,000 pcs/year, Lab coats: 350,000 pcs/year",
    manufacturingMarket: "Samsung, Intel, Foxconn, Tech companies",
    annualCapacity: "1.8 million pieces",
    numberOfEmployees: 1100,
    productionScale: "High-tech production",
    exportBrand: "Samsung, Intel",
    companyCertification: "ISO 9001, ESD Standards, Cleanroom Certified",
  },
  {
    name: "Phu Yen Coastal Fashion",
    shortName: "Phu Yen Coastal",
    taxCode: "5700901234",
    website: "http://phuyencoastal.vn",
    email: "coastal@phuyencoastal.vn",
    emailOwner: "beach@phuyencoastal.vn",
    phoneNumber: "84-257-3901234",
    province: "Phu Yen",
    status: "reviewer",
    companyBranchDtoList: [
      {
        branchName: "Tuy Hoa Head Office",
        address: "678 Tran Hung Dao, Tuy Hoa City, Phu Yen",
        isHeadOffice: true,
        longitude: "109.2957",
        latitude: "13.0955",
      },
    ],
    introduction:
      "Coastal fashion manufacturer inspired by Vietnam's beautiful coastline",
    urlVideo: "phuyencoastal.vn/inspiration",
    manufacturingSector:
      "Beach Fashion; Summer Wear; Tropical Clothing; Vacation Wear",
    productionModels: "FOB, ODM",
    keyProducts:
      "Beach fashion: 1,000,000 pcs/year, Summer wear: 800,000 pcs/year, Vacation wear: 600,000 pcs/year",
    manufacturingMarket:
      "Tropical fashion brands, Beach resorts, Summer collections",
    annualCapacity: "2.9 million pieces",
    numberOfEmployees: 1700,
    productionScale: "Seasonal production",
    exportBrand: "Tropical fashion brands",
    companyCertification: "ISO 9001, OEKO-TEX, Sustainable Fashion",
  },
  {
    name: "Yen Bai Mountain Textiles",
    shortName: "Yen Bai Mountain",
    taxCode: "1700012345",
    website: "http://yenbaimountain.vn",
    email: "mountain@yenbaimountain.vn",
    emailOwner: "highland@yenbaimountain.vn",
    phoneNumber: "84-216-3012345",
    province: "Yen Bai",
    status: "public",
    companyBranchDtoList: [
      {
        branchName: "Yen Bai Head Office",
        address: "345 Tran Hung Dao, Ninh Binh City",
        isHeadOffice: true,
        longitude: "105.9745",
        latitude: "20.2506",
      },
    ],
    introduction:
      "Mountain region textile manufacturer using traditional ethnic techniques",
    urlVideo: "yenbaimountain.vn/ethnic",
    manufacturingSector:
      "Ethnic Textiles; Mountain Wear; Traditional Patterns; Handicrafts",
    productionModels: "OEM, ODM",
    keyProducts:
      "Ethnic textiles: 400,000 pcs/year, Mountain wear: 300,000 pcs/year, Traditional patterns: 250,000 pcs/year",
    manufacturingMarket:
      "Ethnic fashion brands, Cultural organizations, Tourism industry",
    annualCapacity: "1.2 million pieces",
    numberOfEmployees: 800,
    productionScale: "Traditional ethnic production",
    exportBrand: "Ethnic fashion brands",
    companyCertification: "Fair Trade, Heritage Craft, Ethnic Authenticity",
  },
];
